tasklist/urls.py
from django.conf.urls import patterns, include, url
from django.views.generic import RedirectView
from django.conf.urls.static import static
from django.conf import settings

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'tasklist.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^$', RedirectView.as_view(url='tasks/'), name='home'),
    url(r'^tasks/', include('tasks.urls')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^comments/', include('django.contrib.comments.urls')),
    url(r'^accounts/login/$', 'django.contrib.auth.views.login', name='login'),
    url(r'^accounts/logout/$', 'django.contrib.auth.views.logout_then_login', name='logout'),
) + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

tasks/urls.py
from django.conf.urls import patterns, include, url

from .views import (ListTasksView, CreateTaskView, DetailTaskView,
    UpdateTaskView, SetTaskReadyView, SetTaskIncompleteView, SetTaskCompletedView,
    ListIncompleteTasksView, ListUnReviewedTasksView, ListCompletedTasksView,
    ReportHomeView, TasksJsonView)

urlpatterns = patterns('',
    url(r'^$', ListTasksView.as_view(), name='list_tasks'),
    url(r'^incomplete/$',
        ListIncompleteTasksView.as_view(),
        name='list_incomplete_tasks'),
    url(r'^completed/$',
        ListCompletedTasksView.as_view(),
        name='list_completed_tasks'),
    url(r'^unreviewed/$',
        ListUnReviewedTasksView.as_view(),
        name='list_unreviewed_tasks'),
    url(r'^create/$', CreateTaskView.as_view(), name='create_task'),
    url(r'^(?P<pk>\d+)/$', DetailTaskView.as_view(), name='task_detail'),
    url(r'^(?P<pk>\d+)/edit/$', UpdateTaskView.as_view(), name='edit_task'),
    url(r'^(?P<pk>\d+)/incomplete/$',
        SetTaskIncompleteView.as_view(),
        name='set_task_incomplete'),
    url(r'^(?P<pk>\d+)/ready/$',
        SetTaskReadyView.as_view(),
        name='set_task_ready'),
    url(r'^(?P<pk>\d+)/complete/$',
        SetTaskCompletedView.as_view(),
        name='set_task_complete'),
    url(r'report/$',
        ReportHomeView.as_view(),
        name='report_home'),
    url(r'report/task_by_status/json',
        TasksJsonView.as_view(),
        name='task_by_status_json')
)

tasks/models.py
from django.db import models
from django.conf import settings
from django.core.urlresolvers import reverse_lazy
from django.utils import timezone
from django.forms.util import to_current_timezone

from model_utils import Choices

class TimeStampedModel(models.Model):
    """
    An abstract model for the common fields 'created' and 'last_modified'.
    """
    created = models.DateTimeField(auto_now_add=True)
    last_modified = models.DateTimeField(auto_now=True)

    class Meta:
        abstract = True


class Task(TimeStampedModel):
    """
    Model that represent a task.
    """
    PRIORITY_CHOICES = Choices((1, 'low', 'Low'),
                               (2, 'medium', 'Medium'),
                               (3, 'high', 'High'))
    TYPE_CHOICES = Choices((1, 'bug', 'Bug'),
                           (2, 'enhancement', 'Enhancement'),
                           (3, 'task', 'Task'),
                           (4, 'proposal', 'Proposal'))
    STATUS_CHOICES = Choices((1, 'incomplete', 'Incomplete'),
                             (2, 'ready_for_review', 'Ready for Review'),
                             (3, 'complete', 'Complete'))
    created_by = models.ForeignKey(settings.AUTH_USER_MODEL,
                                   null=True,
                                   blank=True,
                                   editable=False,
                                   related_name='tasks')
    title = models.CharField(max_length=255)
    description = models.TextField(blank=True)
    due_date = models.DateField(null=True)
    module = models.CharField(max_length=100, blank=True)
    priority = models.PositiveIntegerField(choices=PRIORITY_CHOICES,
                                           default=PRIORITY_CHOICES.low)
    assigned_user = models.ForeignKey(settings.AUTH_USER_MODEL,
                                      null=True,
                                      blank=True,
                                      verbose_name="Assigned To",
                                      related_name='assigned_tasks')
    type = models.PositiveIntegerField(choices=TYPE_CHOICES,
                                       default=TYPE_CHOICES.task)
    status = models.PositiveIntegerField(choices=STATUS_CHOICES,
                                         default=STATUS_CHOICES.incomplete,
                                         editable=False)
    # Time at which user submitted it for review
    completed_at = models.DateTimeField(null=True,
                                        blank=True,
                                        editable=False)
    reviewed_by = models.ForeignKey(settings.AUTH_USER_MODEL,
                                    null=True,
                                    blank=True,
                                    editable=False,
                                    related_name='reviewed_tasks')

    class Meta:
        ordering = ['-created']

    def is_due(self):
        """
        Return True if this task crossed due date, otherwise false.
        """
        # Convert to current tz, otherwise we are comparing with utc. the date
        # will be entered respect to our current tz
        date_now = to_current_timezone(timezone.now()).date()
        if not self.is_complete() and self.due_date < date_now:
            return True
        else:
            return False

    def is_due_today(self):
        """
        Check if the task due date is today
        """
        date_now = to_current_timezone(timezone.now()).date()
        if self.due_date == date_now:
            return True
        else:
            return False

    def is_complete(self):
        """
        Returns True if the task is marked as completed.
        """
        if self.status == self.STATUS_CHOICES.complete:
            return True
        else:
            return False

    def is_ready_for_review(self):
        """
        Returns True if the task is marked as ready for review.
        """
        if self.status == self.STATUS_CHOICES.ready_for_review:
            return True
        else:
            return False

    def is_incomplete(self):
        """
        Returns True if the task is marked as not completed.
        """
        if self.status == self.STATUS_CHOICES.incomplete:
            return True
        else:
            return False

    def get_absolute_url(self):
        return reverse_lazy('task_detail', kwargs={'pk': self.pk})

    def __str__(self):
        return self.title

tasks/views.py
import json

from django.shortcuts import render, get_object_or_404
from django.views.generic import (ListView, CreateView, DetailView, UpdateView,
    TemplateView, View)
from django.core.urlresolvers import reverse_lazy
from django.http import HttpResponseRedirect, HttpResponse
from django.utils import timezone
from django.db.models import Count

from braces.views import (LoginRequiredMixin, StaffuserRequiredMixin,
        StaticContextMixin, JSONResponseMixin)
from django_tables2.views import SingleTableMixin, SingleTableView

from .models import Task
from .tables import TaskTable

class BaseListTasksView(LoginRequiredMixin,  SingleTableView):
    """
    The base view that can list all tasks. Other actual view will apply just
    filters on this.
    """
    model = Task
    table_class = TaskTable
    filters = {}
    exclude_filters = {}

    def get_queryset(self):
        """
        Exclude completed tasks from normal listing.
        """
        queryset = super(BaseListTasksView, self).get_queryset()
        if self.filters:
            queryset = queryset.filter(**self.filters)
        if self.exclude_filters:
            queryset = queryset.exclude(**self.exclude_filters)
        return queryset.select_related('assigned_user')


class ListTasksView(BaseListTasksView):
    """
    View to list all tasks excluding 
    """
    exclude_filters = {'status': Task.STATUS_CHOICES.complete}


class ListIncompleteTasksView(StaticContextMixin, BaseListTasksView):
    """
    View to list just incomplete tasks.
    """
    filters = {'status': Task.STATUS_CHOICES.incomplete}
    static_context = {"incomplete_menu": True}


class ListUnReviewedTasksView(StaticContextMixin, BaseListTasksView):
    """
    View to list only the tasks that are ready to be reviewed
    """
    filters = {'status': Task.STATUS_CHOICES.ready_for_review}
    static_context = {"unreviewed_menu": True}


class ListCompletedTasksView(StaticContextMixin, BaseListTasksView):
    """
    View to list only the tasks that are completed.
    """
    filters = {'status': Task.STATUS_CHOICES.complete}
    static_context = {"completed_menu": True}
        
    
class CreateTaskView(LoginRequiredMixin, CreateView):
    """
    View to create new tasks.
    """
    model = Task
    success_url = reverse_lazy('list_tasks')

    def post(self, request, *args, **kwargs):
        """
        Overriding default method to add support of cancel button.
        """
        if 'cancel' in request.POST:
            return HttpResponseRedirect(reverse_lazy('list_tasks'))
        return super(CreateTaskView, self).post(request, *args, **kwargs)

    def form_valid(self, form):
        """
        Overriding default functionality for saving the user who created the
        task.
        """
        self.object = form.save(commit=False)
        self.object.created_by = self.request.user
        self.object.save()
        return HttpResponseRedirect(reverse_lazy('list_tasks'))


class DetailTaskView(LoginRequiredMixin, DetailView):
    """
    View to show the details of a task.
    """
    model = Task


class UpdateTaskView(LoginRequiredMixin, UpdateView):
    """
    View to update existing task.
    """
    model = Task

    def post(self, request, *args, **kwargs):
        """
        Overriding to handle cancel button.
        """
        if 'cancel' in request.POST:
            self.object = self.get_object()
            return HttpResponseRedirect(self.get_success_url())
        return super(UpdateTaskView, self).post(request, *args, **kwargs)


class SetTaskReadyView(LoginRequiredMixin, View):
    """
    View to set a task ready for review.
    """
    def post(self, request, *args, **kwargs):
        """
        Set the task as ready for review.
        """
        task = get_object_or_404(Task, pk=self.kwargs.get('pk'))
        task.status = Task.STATUS_CHOICES.ready_for_review
        task.completed_at = timezone.now()
        task.save()
        return HttpResponseRedirect(task.get_absolute_url())


class SetTaskIncompleteView(LoginRequiredMixin, View):
    """
    View to set a task back to incomplete
    """
    def post(self, request, *args, **kwargs):
        """
        View to set a task as not ready for review.
        """
        task = get_object_or_404(Task, pk=self.kwargs.get('pk'))
        task.status = Task.STATUS_CHOICES.incomplete
        task.save()
        return HttpResponseRedirect(task.get_absolute_url())
   

class SetTaskCompletedView(LoginRequiredMixin, StaffuserRequiredMixin, View):
    """
    View to set a task as completed
    """
    raise_exception = True

    def post(self, request, *args, **kwargs):
        """
        View to set a task as completed.
        """
        task = get_object_or_404(Task, pk=self.kwargs.get('pk'))
        task.status = Task.STATUS_CHOICES.complete
        task.reviewed_by = request.user
        task.save()
        return HttpResponseRedirect(task.get_absolute_url())

class ReportHomeView(LoginRequiredMixin, TemplateView):
    """
    View to render template for report home view
    """
    template_name = 'tasks/report.html'

    def get_context_data(self, **kwargs):
        """
        Adding some data to the context
        """
        context = super(ReportHomeView, self).get_context_data(**kwargs)
        tasks = Task.objects.all()
        incomplete_tasks = tasks.filter(
                                status=Task.STATUS_CHOICES.incomplete)
        unreviewed_tasks = tasks.filter(
                                status=Task.STATUS_CHOICES.ready_for_review)
        completed_tasks = tasks.filter(
                                status=Task.STATUS_CHOICES.complete)
        context['incomplete_task_count'] = incomplete_tasks.count()
        context['unreviewed_tasks_count'] = unreviewed_tasks.count()
        context['completed_tasks'] = completed_tasks.count()
        context['report_menu'] = True
        return context

class TasksJsonView(LoginRequiredMixin, JSONResponseMixin, View):
    """
    Returns the task by its status
    """
    def get(self, request, *args, **kwargs):
        """
        Get all task and return a json data of tasks 
        by its status
        """
        tasks = Task.objects.all()
        tasks_by_status = (
            tasks.values('status'
                         ).annotate(count=Count('status')
                         ).order_by('-count'))
        for item in tasks_by_status:
            item['label'] = Task.STATUS_CHOICES[item.get('status')]
            item['data'] = item.get('count')
            del item['status']
            del item['count']
        task_by_module = (
            tasks.values('module'
                         ).annotate(count=Count('module')
                         ).order_by('-count'))
        for item in task_by_module:
            item['label'] = item.get('module')
            item['data'] = item.get('count')
            del item['module']
            del item['count']
        response = {
            'task_by_status' : list(tasks_by_status),
            'task_by_module' : list(task_by_module)
        }
        return self.render_json_response(response)

tasks/templates/tasks/report.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block content %}
<div class="row-fluid">
	<div class="col-md-4 text-center">
		<input type="text" value="{{ incomplete_task_count }}" class="dial" data-readOnly=true>
		<h3><small>Incomplete Tasks</small></h3>
	</div>
	<div class="col-md-4 text-center">
		<input type="text" value="{{ unreviewed_tasks_count }}" class="dial" data-fgColor="#666666" data-readOnly=true>
		<h3><small>Unreviewed Tasks<small></h3>
	</div>
	<div class="col-md-4 text-center">
		<input type="text" value="{{completed_tasks}}" class="dial" data-fgColor="#66CC66" data-readOnly=true>
		<h3><small>Completed Tasks<small></h3>
	</div>
	<div class="clearfix"></div>
	<br><br>
	<div class="col-md-12">
		<div class="col-md-6">
			<div class="panel panel-default">
				<div class="panel-heading">
					<h3 class="panel-title">Tasks By Status</h3>
				</div>
				<div class="panel-body">
					<div class="status_chart" style="height:300px"></div>
				</div>
			</div>
		</div>
		<div class="col-md-6">
			<div class="panel panel-default">
				<div class="panel-heading">
					<h3 class="panel-title">Tasks By Model</h3>
				</div>
				<div class="panel-body">
					<div class="module_chart" style="height:300px"></div>
				</div>
			</div>
		</div>
	</div>
</div>
{% endblock %}

{% block extra_scripts %}
<script type="text/javascript">
	var urls = {
		report_json_url : "{% url 'task_by_status_json' %}"
	}
</script>
<script src="{% static 'js/jquery_knob/jquery.knob.js' %}"></script>
<script src="{% static 'js/flot/jquery.flot.min.js' %}"></script>
<script src="{% static 'js/flot/jquery.flot.pie.js' %}"></script>
<script src="{% static 'js/graph.js' %}"></script>
{% endblock %}

tasks/templates/tasks/task_detail.html
{% extends 'base.html' %}
{% load comments %}
{% load crispy_forms_tags %}
{% load humanize %}

{% block content %}

{% if not task.is_complete %}
    {% if task.is_due %}
    <div class="alert alert-danger alert-dismissable">
        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
        <strong>Rush!</strong> This task is due!
    </div>
    {% endif %}
    {% if task.is_due_today %}
    <div class="alert alert-warning alert-dismissable">
        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
        <strong>Quick!</strong> This task needs to be done today!
    </div>
    {% endif %}
{% endif %}

<div class="panel panel-{% if task.is_complete %}success{% elif task.is_due %}warning{% else %}info{% endif %}">
    <div class="panel-heading">
        {{ task.title }} 
        <a href="{% url 'edit_task' pk=task.pk %}" class="btn btn-default btn-xs"><span class="glyphicon glyphicon-edit"></span></a>
        <span class="badge pull-right">{{ task.get_type_display }}</span>
    </div>
    <div class="panel-body">
        <table class="table table-condensed">
            <tbody>
            <tr>
                <td><strong>Description</strong></td><td>{{ task.description }}</td>
            </tr>
            <tr>
                <td><strong>Due date</strong></td><td>{{ task.due_date|naturalday }}</td>
            </tr>
            <tr>
                <td><strong>Created by</strong></td><td>{{ task.created_by.get_full_name|default:task.created_by }}</td>
            </tr>
            <tr>
                <td><strong>Priority</strong></td><td>{{ task.get_priority_display }}</td>
            </tr>
            <tr>
                <td><strong>Assigned to</strong></td><td>{{ task.assigned_user.get_full_name|default:task.assigned_user }}</td>
            </tr>
            <tr>
                <td><strong>Module</strong></td><td>{{ task.module }}</td>
            </tr>
            <tr>
                <td><strong>Status</strong></td>
                <td>
                    {{ task.get_status_display }}
                {% if task.is_incomplete %}
                    <form action="{% url 'set_task_ready' pk=task.pk %}" method="post">
                        {% csrf_token %}
                        <button type="submit" class="btn btn-default btn-xs">Ready for Review</button>
                    </form>
                {% elif task.is_ready_for_review %}
                    <form action="{% url 'set_task_incomplete' pk=task.pk %}" method="post">
                        {% csrf_token %}
                        <button type="submit" class="btn btn-default btn-xs">Mark as Incomplete</button>
                    </form>
                {% endif %}
                {% if user.is_staff and not task.is_complete %}
                    <form action="{% url 'set_task_complete' pk=task.pk %}" method="post">
                        {% csrf_token %}
                        <button type="submit" class="btn btn-default btn-xs">Mark as Completed</button>
                    </form>
                {% endif %}
                </td>
            </tr>
            {% if task.is_ready_for_review or task.is_complete %}
            <tr>
                <td><strong>Completed at</strong></td><td>{{ task.completed_at|naturaltime }}</td>
            </tr>
            {% endif %}
            {% if task.is_complete %}
            <tr>
                <td><strong>Reviewed by</strong></td><td>{{ task.reviewed_by.get_full_name|default:task.reviewed_by }}</td>
            </tr>
            <!--<tr>-->
                <!--<td><strong>Reviewed at</strong></td><td>{{ task.reviewed_at }}</td>-->
            <!--</tr>-->
            {% endif %}
            </tbody>
        </table>
    </div>
</div>

<div class="panel panel-default">
    <div class="panel-header"><strong>Follow up</strong></div>
    <div class="panel-body">
        {% get_comment_list for task as comment_list %}
        {% for comment in comment_list %}
            <div class="panel">
                <div class="panel-footer">
                    #{{ forloop.counter }} {{ comment.user.get_full_name|default:comment.user }} at {{ comment.submit_date|naturaltime }}
                </div>
                <div class="panel-body">
                    <a name="c{{ comment.id }}"></a>
                    {{ comment.comment }}
                </div>
            </div>
        {% endfor %}
    </div>

    <div class="panel">
        <div class="panel-body">
            {% get_comment_form for task as form %}
        <table>
        <form action="{% comment_form_target %}" method="POST">
            {% csrf_token %}
            <div id="div_id_comment" class="form-group">
                <label for="id_comment" class="control-label ">Comment</label>
                <div class="controls ">
                    <textarea id="id_comment" name="comment" cols="20" class="form-control" rows="2"></textarea>
                <div>
            </div>
            {{ form.content_type }}
            {{ form.object_pk }}
            {{ form.timestamp }}
            {{ form.security_hash }}
            <input type="hidden" name="next" value="{% url 'task_detail' task.pk %}" />
            <input type="submit" class="btn btn-default btn-xs" value="Add" id="id_submit" />
        </form>
        </table>
        </div>
    </div>
</div>

{% endblock %}

tasks/templates/tasks/task_form.html
{% extends "base.html" %} 
{% load crispy_forms_tags %}


{% block content %}
<div class="row">
    <div class="col-md-4 col-md-offset-3">
        <form method="post">
            {% csrf_token %}
            {{ form|crispy }}
            <button type="submit" name="submit" class="btn btn-primary">Save</button>
            <button type="submit" name="cancel" class="btn btn-default">Cancel</button>
        </form>
    </div>
</div>
{% endblock %}

tasks/templates/tasks/task_list.html
{% extends "base.html" %}
{% load render_table from django_tables2 %}

{% block content %}
    {% render_table table %}
{% endblock %}